services:
  db:
    image: postgres:16
    container_name: matt-init-example-project-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - matt-init-example-project_pgdata:/var/lib/postgresql/data

volumes:
  matt-init-example-project_pgdata:
